job('Java-Maven-Project-Via-DSL') {
    description("Maven job generated by the DSL on ${new Date()}, the project is hosted on github")
    scm {
        git("https://github.com/maheshbhutkar/java-maven-jenkins-project.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}